const humans = [
	{
		id: 1,
		name: 'João Silva',
		age: 32,
		city: 'São Paulo',
		email: 'joao.silva@example.com',
		title: 'Engenheiro de Software',
	},
	{
		id: 2,
		name: 'Mariana Santos',
		age: 28,
		city: 'Rio de Janeiro',
		email: 'mariana.santos@example.com',
		title: 'Cientista de Dados',
	},
	{
		id: 3,
		name: 'Carlos Oliveira',
		age: 35,
		city: 'Belo Horizonte',
		email: 'carlos.oliveira@example.com',
		title: 'Gerente de Produtos',
	},
	{
		id: 4,
		name: 'Ana Souza',
		age: 29,
		city: 'Salvador',
		email: 'ana.souza@example.com',
		title: 'Designer UX',
	},
	{
		id: 5,
		name: 'Rafael Pereira',
		age: 27,
		city: 'Porto Alegre',
		email: 'rafael.pereira@example.com',
		title: 'Desenvolvedor Web',
	},
	{
		id: 6,
		name: 'Fernanda Almeida',
		age: 31,
		city: 'Recife',
		email: 'fernanda.almeida@example.com',
		title: 'Designer Gráfico',
	},
	{
		id: 7,
		name: 'Lucas Rodrigues',
		age: 30,
		city: 'Brasília',
		email: 'lucas.rodrigues@example.com',
		title: 'Analista de Negócios',
	},
	{
		id: 8,
		name: 'Beatriz Costas',
		age: 26,
		city: 'Curitiba',
		email: 'beatriz.costa@example.com',
		title: 'Especialista em Marketing',
	},
	{
		id: 9,
		name: 'Thiago Santos',
		age: 33,
		city: 'Fortaleza',
		email: 'thiago.santos@example.com',
		title: 'Desenvolvedor Frontend',
	},
	{
		id: 10,
		name: 'Laura Oliveira',
		age: 28,
		city: 'Manaus',
		email: 'laura.oliveira@example.com',
		title: 'Gerente de Projetos',
	},
];

const namesAndTitles = humans.map(({ name, title }) => ({ name, title }));
console.log(namesAndTitles);
